FROM apache/kafka:latest

# KRaft mode - minimal configuration (defaults from docker-compose-with-grafana.yml)
ENV KAFKA_NODE_ID=1
ENV KAFKA_PROCESS_ROLES=broker,controller
ENV KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9094
ENV KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER

# DUAL LISTENERS - Internal and External
ENV KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:9093,CONTROLLER://0.0.0.0:9094
ENV KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9093
ENV KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,CONTROLLER:PLAINTEXT
ENV KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT

# Minimal topic settings
ENV KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
ENV KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
ENV KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1
ENV KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
ENV KAFKA_NUM_PARTITIONS=1
ENV KAFKA_DEFAULT_REPLICATION_FACTOR=1

# Connection and timeout settings
ENV KAFKA_CONNECTIONS_MAX_IDLE_MS=600000
ENV KAFKA_REQUEST_TIMEOUT_MS=30000
ENV KAFKA_METADATA_MAX_AGE_MS=300000

# Producer settings for better reliability
ENV KAFKA_COMPRESSION_TYPE=gzip
ENV KAFKA_MIN_INSYNC_REPLICAS=1
ENV KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false

# Consumer settings
ENV KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS=3000
ENV KAFKA_GROUP_SESSION_TIMEOUT_MS=180000
ENV KAFKA_GROUP_HEARTBEAT_INTERVAL_MS=3000
ENV KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=300000

# 2-hour retention policy and logs
ENV KAFKA_LOG_RETENTION_HOURS=2
ENV KAFKA_LOG_RETENTION_MS=7200000
ENV KAFKA_LOG_RETENTION_BYTES=5368709120
ENV KAFKA_LOG_SEGMENT_BYTES=268435456
ENV KAFKA_LOG_SEGMENT_MS=3600000
ENV KAFKA_LOG_CLEANUP_POLICY=delete
ENV KAFKA_LOG_RETENTION_CHECK_INTERVAL_MS=300000

# Optimized JVM settings and data directory
ENV KAFKA_HEAP_OPTS="-Xmx3g -Xms1g -XX:+UseG1GC"
ENV KAFKA_LOG_DIRS=/var/lib/kafka/data

# Required for KRaft
ENV CLUSTER_ID=MkU3OEVBNTcwNTJENDM2Qk

EXPOSE 9092 9093